package com.gmsanubis.mystuff.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import javax.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;


/**
 * A Brand is composed of these following attributes:
 * <ul>
 *   <li><strong>String</strong> id
 *   <p><i>Auto generated by MongoDB</i></p></li>
 *   <li><strong>String</strong> name
 *   <p><i>Can't be blank</i></p></li>
 *   <li><strong>String</strong> logoPath
 *   <p><i>Can't be blank</i></p></li>
 * </ul>
 * This object is annotated as a MongoDb Document.
 *
 * @see org.springframework.data.mongodb.core.mapping.Document
 */
@Getter
@Setter
@Document(collection = "Brands")
public class Brand {

  @Id
  private java.lang.String id;

  @NotBlank
  @Field(value = "name")
  private String name;

  @NotBlank
  @Field(value="logo_path")
  private String logoPath;
}
